project_name: nekkus-gate

builds:
  - id: nekkus-gate
    main: ./cmd
    binary: nekkus-gate
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_arm64"
    wrap_in_directory: com.nekkus.gate
    files:
      - src: release_assets/manifest.json
        dst: .
        strip_parent: true

release:
  github:
    owner: GalitskyKK
    name: nekkus-gate
  name_template: "v{{ .Version }}"
